<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lidarslam_registration_plugin_template</name>
  <version>0.1.0</version>
  <description>C++14 template for an external lidarslam registration plugin.</description>
  <maintainer email="rsasaki0109@gmail.com">sasaki</maintainer>
  <license>BSD-2-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>pluginlib</depend>
  <depend>lidarslam_plugin_interfaces</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>lidarslam_registration_loader</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
