# Copyright 2026 Sasaki
# All rights reserved.
#
# Software License Agreement (BSD 2-Clause Simplified License)
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


# Deterministic install-time generator for one registration plugin class.
# The DSO is hashed after installation, so a configure-time manifest can never
# accidentally describe a later/relinked binary.  All REGISTRATION_CONTRACT_*
# variables are supplied by the package CMakeLists.txt through install(CODE).

if(NOT DEFINED REGISTRATION_CONTRACT_XML OR
  NOT DEFINED REGISTRATION_CONTRACT_DSO OR
  NOT DEFINED REGISTRATION_CONTRACT_CLASS_ID)
  message(FATAL_ERROR "registration contract generator requires XML, DSO, and class ID")
endif()

if(NOT EXISTS "${REGISTRATION_CONTRACT_XML}" OR
  NOT EXISTS "${REGISTRATION_CONTRACT_DSO}")
  message(FATAL_ERROR
    "registration contract inputs are absent after install: XML=${REGISTRATION_CONTRACT_XML} DSO=${REGISTRATION_CONTRACT_DSO}")
endif()

file(SHA256 "${REGISTRATION_CONTRACT_XML}" REGISTRATION_CONTRACT_XML_SHA256)
file(SIZE "${REGISTRATION_CONTRACT_XML}" REGISTRATION_CONTRACT_XML_SIZE)
file(SHA256 "${REGISTRATION_CONTRACT_DSO}" REGISTRATION_CONTRACT_DSO_SHA256)
file(SIZE "${REGISTRATION_CONTRACT_DSO}" REGISTRATION_CONTRACT_DSO_SIZE)

set(REGISTRATION_CONTRACT_SCHEMA "lidarslam-registration-contract-manifest-v1")
set(REGISTRATION_CONTRACT_SCHEMA_VERSION 1)
set(REGISTRATION_CONTRACT_ABI_EPOCH "lidarslam.registration.cpp14.abi1")
set(REGISTRATION_CONTRACT_INTERFACE_SHA256
  "de43eef540d5e6836ed41d69074590641b810acc0f6661eb73c4f0e90d4c369c")

if(NOT DEFINED REGISTRATION_CONTRACT_CANCELLATION_MODEL)
  set(REGISTRATION_CONTRACT_CANCELLATION_MODEL 0)
endif()

set(REGISTRATION_CONTRACT_IDENTITY
  "schema=${REGISTRATION_CONTRACT_SCHEMA}|schema_version=${REGISTRATION_CONTRACT_SCHEMA_VERSION}|class_id=${REGISTRATION_CONTRACT_CLASS_ID}|plugin_xml_sha256=${REGISTRATION_CONTRACT_XML_SHA256}|plugin_xml_size_bytes=${REGISTRATION_CONTRACT_XML_SIZE}|dso_sha256=${REGISTRATION_CONTRACT_DSO_SHA256}|dso_size_bytes=${REGISTRATION_CONTRACT_DSO_SIZE}|abi_epoch=${REGISTRATION_CONTRACT_ABI_EPOCH}|toolchain_tag=${REGISTRATION_CONTRACT_TOOLCHAIN_TAG}|interface_contract_sha256=${REGISTRATION_CONTRACT_INTERFACE_SHA256}|api_min_major=${REGISTRATION_CONTRACT_API_MIN_MAJOR}|api_min_minor=${REGISTRATION_CONTRACT_API_MIN_MINOR}|api_max_major=${REGISTRATION_CONTRACT_API_MAX_MAJOR}|api_max_minor=${REGISTRATION_CONTRACT_API_MAX_MINOR}|required_capability_bits=${REGISTRATION_CONTRACT_REQUIRED_CAPABILITY_BITS}|optional_capability_bits=${REGISTRATION_CONTRACT_OPTIONAL_CAPABILITY_BITS}|target_policy=${REGISTRATION_CONTRACT_TARGET_POLICY}|correspondence_metric=${REGISTRATION_CONTRACT_CORRESPONDENCE_METRIC}|thread_model=${REGISTRATION_CONTRACT_THREAD_MODEL}|cancellation_model=${REGISTRATION_CONTRACT_CANCELLATION_MODEL}|config_schema_id=${REGISTRATION_CONTRACT_CONFIG_SCHEMA_ID}|config_schema_version=${REGISTRATION_CONTRACT_CONFIG_SCHEMA_VERSION}|config_schema_sha256=${REGISTRATION_CONTRACT_CONFIG_SCHEMA_SHA256}")
string(SHA256 REGISTRATION_CONTRACT_MANIFEST_SHA256 "${REGISTRATION_CONTRACT_IDENTITY}")

string(REGEX REPLACE "[^A-Za-z0-9_-]" "_" REGISTRATION_CONTRACT_CLASS_FILE
  "${REGISTRATION_CONTRACT_CLASS_ID}")
get_filename_component(REGISTRATION_CONTRACT_XML_NAME "${REGISTRATION_CONTRACT_XML}" NAME)
get_filename_component(REGISTRATION_CONTRACT_XML_DIR "${REGISTRATION_CONTRACT_XML}" DIRECTORY)
set(REGISTRATION_CONTRACT_OUTPUT
  "${REGISTRATION_CONTRACT_XML_DIR}/${REGISTRATION_CONTRACT_XML_NAME}.${REGISTRATION_CONTRACT_CLASS_FILE}.contract.json")

file(WRITE "${REGISTRATION_CONTRACT_OUTPUT}" "{\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"schema\": \"${REGISTRATION_CONTRACT_SCHEMA}\",\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"schema_version\": ${REGISTRATION_CONTRACT_SCHEMA_VERSION},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"class_id\": \"${REGISTRATION_CONTRACT_CLASS_ID}\",\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"plugin_xml_sha256\": \"${REGISTRATION_CONTRACT_XML_SHA256}\",\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"plugin_xml_size_bytes\": ${REGISTRATION_CONTRACT_XML_SIZE},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"dso_sha256\": \"${REGISTRATION_CONTRACT_DSO_SHA256}\",\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"dso_size_bytes\": ${REGISTRATION_CONTRACT_DSO_SIZE},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"abi_epoch\": \"${REGISTRATION_CONTRACT_ABI_EPOCH}\",\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"toolchain_tag\": \"${REGISTRATION_CONTRACT_TOOLCHAIN_TAG}\",\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"interface_contract_sha256\": \"${REGISTRATION_CONTRACT_INTERFACE_SHA256}\",\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"api_min_major\": ${REGISTRATION_CONTRACT_API_MIN_MAJOR},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"api_min_minor\": ${REGISTRATION_CONTRACT_API_MIN_MINOR},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"api_max_major\": ${REGISTRATION_CONTRACT_API_MAX_MAJOR},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"api_max_minor\": ${REGISTRATION_CONTRACT_API_MAX_MINOR},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"required_capability_bits\": ${REGISTRATION_CONTRACT_REQUIRED_CAPABILITY_BITS},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"optional_capability_bits\": ${REGISTRATION_CONTRACT_OPTIONAL_CAPABILITY_BITS},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"target_policy\": ${REGISTRATION_CONTRACT_TARGET_POLICY},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"correspondence_metric\": ${REGISTRATION_CONTRACT_CORRESPONDENCE_METRIC},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"thread_model\": ${REGISTRATION_CONTRACT_THREAD_MODEL},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"cancellation_model\": ${REGISTRATION_CONTRACT_CANCELLATION_MODEL},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"config_schema_id\": \"${REGISTRATION_CONTRACT_CONFIG_SCHEMA_ID}\",\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"config_schema_version\": ${REGISTRATION_CONTRACT_CONFIG_SCHEMA_VERSION},\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"config_schema_sha256\": \"${REGISTRATION_CONTRACT_CONFIG_SCHEMA_SHA256}\",\n")
file(APPEND "${REGISTRATION_CONTRACT_OUTPUT}" "  \"manifest_sha256\": \"${REGISTRATION_CONTRACT_MANIFEST_SHA256}\"\n}\n")
file(CHMOD "${REGISTRATION_CONTRACT_OUTPUT}" PERMISSIONS OWNER_READ GROUP_READ WORLD_READ)
