#!/usr/bin/env bash
set -euo pipefail
DATA_DIR="${1:-$HOME/autoware_data}"
echo "Downloading Autoware artifacts to ${DATA_DIR}..."

mkdir -p ${DATA_DIR}/yabloc_pose_initializer
[ -f ${DATA_DIR}/yabloc_pose_initializer/resources.tar.gz ] || { wget -q -O ${DATA_DIR}/yabloc_pose_initializer/resources.tar.gz "https://s3.ap-northeast-2.wasabisys.com/pinto-model-zoo/136_road-segmentation-adas-0001/resources.tar.gz" && echo "  OK: resources.tar.gz"; } || echo "  FAIL: resources.tar.gz"
tar xzf ${DATA_DIR}/yabloc_pose_initializer/resources.tar.gz -C ${DATA_DIR}/yabloc_pose_initializer/ 2>/dev/null || true
mkdir -p ${DATA_DIR}/bevfusion
[ -f ${DATA_DIR}/bevfusion/bevfusion_lidar.onnx ] || { wget -q -O ${DATA_DIR}/bevfusion/bevfusion_lidar.onnx "https://awf.ml.dev.web.auto/perception/models/bevfusion/t4base_120m/v2/bevfusion_lidar.onnx" && echo "  OK: bevfusion_lidar.onnx"; } || echo "  FAIL: bevfusion_lidar.onnx"
[ -f ${DATA_DIR}/bevfusion/bevfusion_camera_lidar.onnx ] || { wget -q -O ${DATA_DIR}/bevfusion/bevfusion_camera_lidar.onnx "https://awf.ml.dev.web.auto/perception/models/bevfusion/t4base_120m/v2/bevfusion_camera_lidar.onnx" && echo "  OK: bevfusion_camera_lidar.onnx"; } || echo "  FAIL: bevfusion_camera_lidar.onnx"
[ -f ${DATA_DIR}/bevfusion/bevfusion_image_backbone.onnx ] || { wget -q -O ${DATA_DIR}/bevfusion/bevfusion_image_backbone.onnx "https://awf.ml.dev.web.auto/perception/models/bevfusion/t4base_120m/v2/bevfusion_image_backbone.onnx" && echo "  OK: bevfusion_image_backbone.onnx"; } || echo "  FAIL: bevfusion_image_backbone.onnx"
[ -f ${DATA_DIR}/bevfusion/ml_package_bevfusion_lidar.param.yaml ] || { wget -q -O ${DATA_DIR}/bevfusion/ml_package_bevfusion_lidar.param.yaml "https://awf.ml.dev.web.auto/perception/models/bevfusion/t4base_120m/v2/ml_package_bevfusion_lidar.param.yaml" && echo "  OK: ml_package_bevfusion_lidar.param.yaml"; } || echo "  FAIL: ml_package_bevfusion_lidar.param.yaml"
[ -f ${DATA_DIR}/bevfusion/ml_package_bevfusion_camera_lidar.param.yaml ] || { wget -q -O ${DATA_DIR}/bevfusion/ml_package_bevfusion_camera_lidar.param.yaml "https://awf.ml.dev.web.auto/perception/models/bevfusion/t4base_120m/v2/ml_package_bevfusion_camera_lidar.param.yaml" && echo "  OK: ml_package_bevfusion_camera_lidar.param.yaml"; } || echo "  FAIL: ml_package_bevfusion_camera_lidar.param.yaml"
[ -f ${DATA_DIR}/bevfusion/detection_class_remapper.param.yaml ] || { wget -q -O ${DATA_DIR}/bevfusion/detection_class_remapper.param.yaml "https://awf.ml.dev.web.auto/perception/models/bevfusion/t4base_120m/v2/detection_class_remapper.param.yaml" && echo "  OK: detection_class_remapper.param.yaml"; } || echo "  FAIL: detection_class_remapper.param.yaml"
mkdir -p ${DATA_DIR}/camera_streampetr
[ -f ${DATA_DIR}/camera_streampetr/simplify_pts_head_memory.onnx ] || { wget -q -O ${DATA_DIR}/camera_streampetr/simplify_pts_head_memory.onnx "https://awf.ml.dev.web.auto/perception/models/streampetr/v1/simplify_pts_head_memory.onnx" && echo "  OK: simplify_pts_head_memory.onnx"; } || echo "  FAIL: simplify_pts_head_memory.onnx"
[ -f ${DATA_DIR}/camera_streampetr/simplify_position_embedding.onnx ] || { wget -q -O ${DATA_DIR}/camera_streampetr/simplify_position_embedding.onnx "https://awf.ml.dev.web.auto/perception/models/streampetr/v1/simplify_position_embedding.onnx" && echo "  OK: simplify_position_embedding.onnx"; } || echo "  FAIL: simplify_position_embedding.onnx"
[ -f ${DATA_DIR}/camera_streampetr/simplify_extract_img_feat.onnx ] || { wget -q -O ${DATA_DIR}/camera_streampetr/simplify_extract_img_feat.onnx "https://awf.ml.dev.web.auto/perception/models/streampetr/v1/simplify_extract_img_feat.onnx" && echo "  OK: simplify_extract_img_feat.onnx"; } || echo "  FAIL: simplify_extract_img_feat.onnx"
[ -f ${DATA_DIR}/camera_streampetr/ml_package_camera_streampetr.param.yaml ] || { wget -q -O ${DATA_DIR}/camera_streampetr/ml_package_camera_streampetr.param.yaml "https://awf.ml.dev.web.auto/perception/models/streampetr/v1/ml_package_camera_streampetr.param.yaml" && echo "  OK: ml_package_camera_streampetr.param.yaml"; } || echo "  FAIL: ml_package_camera_streampetr.param.yaml"
mkdir -p ${DATA_DIR}/tensorrt_bevdet
[ -f ${DATA_DIR}/tensorrt_bevdet/tensorrt_bevdet.tar.gz ] || { wget -q -O ${DATA_DIR}/tensorrt_bevdet/tensorrt_bevdet.tar.gz "https://autoware-files.s3.us-west-2.amazonaws.com/models/tensorrt_bevdet.tar.gz" && echo "  OK: tensorrt_bevdet.tar.gz"; } || echo "  FAIL: tensorrt_bevdet.tar.gz"
tar xzf ${DATA_DIR}/tensorrt_bevdet/tensorrt_bevdet.tar.gz -C ${DATA_DIR}/tensorrt_bevdet/ 2>/dev/null || true
mkdir -p ${DATA_DIR}/image_projection_based_fusion
[ -f ${DATA_DIR}/image_projection_based_fusion/pts_voxel_encoder_pointpainting.onnx ] || { wget -q -O ${DATA_DIR}/image_projection_based_fusion/pts_voxel_encoder_pointpainting.onnx "https://awf.ml.dev.web.auto/perception/models/pointpainting/v5/pts_voxel_encoder_pointpainting.onnx" && echo "  OK: pts_voxel_encoder_pointpainting.onnx"; } || echo "  FAIL: pts_voxel_encoder_pointpainting.onnx"
[ -f ${DATA_DIR}/image_projection_based_fusion/pts_backbone_neck_head_pointpainting.onnx ] || { wget -q -O ${DATA_DIR}/image_projection_based_fusion/pts_backbone_neck_head_pointpainting.onnx "https://awf.ml.dev.web.auto/perception/models/pointpainting/v5/pts_backbone_neck_head_pointpainting.onnx" && echo "  OK: pts_backbone_neck_head_pointpainting.onnx"; } || echo "  FAIL: pts_backbone_neck_head_pointpainting.onnx"
[ -f ${DATA_DIR}/image_projection_based_fusion/detection_class_remapper.param.yaml ] || { wget -q -O ${DATA_DIR}/image_projection_based_fusion/detection_class_remapper.param.yaml "https://awf.ml.dev.web.auto/perception/models/pointpainting/v5/detection_class_remapper.param.yaml" && echo "  OK: detection_class_remapper.param.yaml"; } || echo "  FAIL: detection_class_remapper.param.yaml"
[ -f ${DATA_DIR}/image_projection_based_fusion/pointpainting_ml_package.param.yaml ] || { wget -q -O ${DATA_DIR}/image_projection_based_fusion/pointpainting_ml_package.param.yaml "https://awf.ml.dev.web.auto/perception/models/pointpainting/v5/pointpainting_ml_package.param.yaml" && echo "  OK: pointpainting_ml_package.param.yaml"; } || echo "  FAIL: pointpainting_ml_package.param.yaml"
mkdir -p ${DATA_DIR}/lidar_apollo_instance_segmentation
[ -f ${DATA_DIR}/lidar_apollo_instance_segmentation/vlp-16.onnx ] || { wget -q -O ${DATA_DIR}/lidar_apollo_instance_segmentation/vlp-16.onnx "https://awf.ml.dev.web.auto/perception/models/lidar_apollo_instance_segmentation/vlp-16.onnx" && echo "  OK: vlp-16.onnx"; } || echo "  FAIL: vlp-16.onnx"
[ -f ${DATA_DIR}/lidar_apollo_instance_segmentation/hdl-64.onnx ] || { wget -q -O ${DATA_DIR}/lidar_apollo_instance_segmentation/hdl-64.onnx "https://awf.ml.dev.web.auto/perception/models/lidar_apollo_instance_segmentation/hdl-64.onnx" && echo "  OK: hdl-64.onnx"; } || echo "  FAIL: hdl-64.onnx"
[ -f ${DATA_DIR}/lidar_apollo_instance_segmentation/vls-128.onnx ] || { wget -q -O ${DATA_DIR}/lidar_apollo_instance_segmentation/vls-128.onnx "https://awf.ml.dev.web.auto/perception/models/lidar_apollo_instance_segmentation/vls-128.onnx" && echo "  OK: vls-128.onnx"; } || echo "  FAIL: vls-128.onnx"
mkdir -p ${DATA_DIR}/lidar_centerpoint
[ -f ${DATA_DIR}/lidar_centerpoint/pts_voxel_encoder_centerpoint.onnx ] || { wget -q -O ${DATA_DIR}/lidar_centerpoint/pts_voxel_encoder_centerpoint.onnx "https://awf.ml.dev.web.auto/perception/models/centerpoint/v3/pts_voxel_encoder_centerpoint.onnx" && echo "  OK: pts_voxel_encoder_centerpoint.onnx"; } || echo "  FAIL: pts_voxel_encoder_centerpoint.onnx"
[ -f ${DATA_DIR}/lidar_centerpoint/pts_backbone_neck_head_centerpoint.onnx ] || { wget -q -O ${DATA_DIR}/lidar_centerpoint/pts_backbone_neck_head_centerpoint.onnx "https://awf.ml.dev.web.auto/perception/models/centerpoint/v3/pts_backbone_neck_head_centerpoint.onnx" && echo "  OK: pts_backbone_neck_head_centerpoint.onnx"; } || echo "  FAIL: pts_backbone_neck_head_centerpoint.onnx"
[ -f ${DATA_DIR}/lidar_centerpoint/pts_voxel_encoder_centerpoint_tiny.onnx ] || { wget -q -O ${DATA_DIR}/lidar_centerpoint/pts_voxel_encoder_centerpoint_tiny.onnx "https://awf.ml.dev.web.auto/perception/models/centerpoint/v3/pts_voxel_encoder_centerpoint_tiny.onnx" && echo "  OK: pts_voxel_encoder_centerpoint_tiny.onnx"; } || echo "  FAIL: pts_voxel_encoder_centerpoint_tiny.onnx"
[ -f ${DATA_DIR}/lidar_centerpoint/pts_backbone_neck_head_centerpoint_tiny.onnx ] || { wget -q -O ${DATA_DIR}/lidar_centerpoint/pts_backbone_neck_head_centerpoint_tiny.onnx "https://awf.ml.dev.web.auto/perception/models/centerpoint/v3/pts_backbone_neck_head_centerpoint_tiny.onnx" && echo "  OK: pts_backbone_neck_head_centerpoint_tiny.onnx"; } || echo "  FAIL: pts_backbone_neck_head_centerpoint_tiny.onnx"
[ -f ${DATA_DIR}/lidar_centerpoint/centerpoint_ml_package.param.yaml ] || { wget -q -O ${DATA_DIR}/lidar_centerpoint/centerpoint_ml_package.param.yaml "https://awf.ml.dev.web.auto/perception/models/centerpoint/v3/centerpoint_ml_package.param.yaml" && echo "  OK: centerpoint_ml_package.param.yaml"; } || echo "  FAIL: centerpoint_ml_package.param.yaml"
[ -f ${DATA_DIR}/lidar_centerpoint/centerpoint_tiny_ml_package.param.yaml ] || { wget -q -O ${DATA_DIR}/lidar_centerpoint/centerpoint_tiny_ml_package.param.yaml "https://awf.ml.dev.web.auto/perception/models/centerpoint/v3/centerpoint_tiny_ml_package.param.yaml" && echo "  OK: centerpoint_tiny_ml_package.param.yaml"; } || echo "  FAIL: centerpoint_tiny_ml_package.param.yaml"
[ -f ${DATA_DIR}/lidar_centerpoint/centerpoint_sigma_ml_package.param.yaml ] || { wget -q -O ${DATA_DIR}/lidar_centerpoint/centerpoint_sigma_ml_package.param.yaml "https://awf.ml.dev.web.auto/perception/models/centerpoint/v3/centerpoint_sigma_ml_package.param.yaml" && echo "  OK: centerpoint_sigma_ml_package.param.yaml"; } || echo "  FAIL: centerpoint_sigma_ml_package.param.yaml"
[ -f ${DATA_DIR}/lidar_centerpoint/detection_class_remapper.param.yaml ] || { wget -q -O ${DATA_DIR}/lidar_centerpoint/detection_class_remapper.param.yaml "https://awf.ml.dev.web.auto/perception/models/centerpoint/v3/detection_class_remapper.param.yaml" && echo "  OK: detection_class_remapper.param.yaml"; } || echo "  FAIL: detection_class_remapper.param.yaml"
[ -f ${DATA_DIR}/lidar_centerpoint/deploy_metadata.yaml ] || { wget -q -O ${DATA_DIR}/lidar_centerpoint/deploy_metadata.yaml "https://awf.ml.dev.web.auto/perception/models/centerpoint/v3/deploy_metadata.yaml" && echo "  OK: deploy_metadata.yaml"; } || echo "  FAIL: deploy_metadata.yaml"
mkdir -p ${DATA_DIR}/lidar_transfusion
[ -f ${DATA_DIR}/lidar_transfusion/transfusion.onnx ] || { wget -q -O ${DATA_DIR}/lidar_transfusion/transfusion.onnx "https://awf.ml.dev.web.auto/perception/models/transfusion/t4xx1_90m/v2.1/transfusion.onnx" && echo "  OK: transfusion.onnx"; } || echo "  FAIL: transfusion.onnx"
[ -f ${DATA_DIR}/lidar_transfusion/transfusion_ml_package.param.yaml ] || { wget -q -O ${DATA_DIR}/lidar_transfusion/transfusion_ml_package.param.yaml "https://awf.ml.dev.web.auto/perception/models/transfusion/t4xx1_90m/v2.1/transfusion_ml_package.param.yaml" && echo "  OK: transfusion_ml_package.param.yaml"; } || echo "  FAIL: transfusion_ml_package.param.yaml"
[ -f ${DATA_DIR}/lidar_transfusion/detection_class_remapper.param.yaml ] || { wget -q -O ${DATA_DIR}/lidar_transfusion/detection_class_remapper.param.yaml "https://awf.ml.dev.web.auto/perception/models/transfusion/t4xx1_90m/v2.1/detection_class_remapper.param.yaml" && echo "  OK: detection_class_remapper.param.yaml"; } || echo "  FAIL: detection_class_remapper.param.yaml"
mkdir -p ${DATA_DIR}/tensorrt_yolox
[ -f ${DATA_DIR}/tensorrt_yolox/yolox-tiny.onnx ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/yolox-tiny.onnx "https://awf.ml.dev.web.auto/perception/models/yolox-tiny.onnx" && echo "  OK: yolox-tiny.onnx"; } || echo "  FAIL: yolox-tiny.onnx"
[ -f ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-opt.onnx ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-opt.onnx "https://awf.ml.dev.web.auto/perception/models/yolox-sPlus-opt.onnx" && echo "  OK: yolox-sPlus-opt.onnx"; } || echo "  FAIL: yolox-sPlus-opt.onnx"
[ -f ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-opt.EntropyV2-calibration.table ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-opt.EntropyV2-calibration.table "https://awf.ml.dev.web.auto/perception/models/yolox-sPlus-opt.EntropyV2-calibration.table" && echo "  OK: yolox-sPlus-opt.EntropyV2-calibration.table"; } || echo "  FAIL: yolox-sPlus-opt.EntropyV2-calibration.table"
[ -f ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-T4-960x960-pseudo-finetune.onnx ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-T4-960x960-pseudo-finetune.onnx "https://awf.ml.dev.web.auto/perception/models/object_detection_yolox_s/v1/yolox-sPlus-T4-960x960-pseudo-finetune.onnx" && echo "  OK: yolox-sPlus-T4-960x960-pseudo-finetune.onnx"; } || echo "  FAIL: yolox-sPlus-T4-960x960-pseudo-finetune.onnx"
[ -f ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-T4-960x960-pseudo-finetune.EntropyV2-calibration.table ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-T4-960x960-pseudo-finetune.EntropyV2-calibration.table "https://awf.ml.dev.web.auto/perception/models/object_detection_yolox_s/v1/yolox-sPlus-T4-960x960-pseudo-finetune.EntropyV2-calibration.table" && echo "  OK: yolox-sPlus-T4-960x960-pseudo-finetune.EntropyV2-calibration.table"; } || echo "  FAIL: yolox-sPlus-T4-960x960-pseudo-finetune.EntropyV2-calibration.table"
[ -f ${DATA_DIR}/tensorrt_yolox/label.txt ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/label.txt "https://awf.ml.dev.web.auto/perception/models/label.txt" && echo "  OK: label.txt"; } || echo "  FAIL: label.txt"
[ -f ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.onnx ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.onnx "https://awf.ml.dev.web.auto/perception/models/object_detection_semseg_yolox_s/v1/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.onnx" && echo "  OK: yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.onnx"; } || echo "  FAIL: yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.onnx"
[ -f ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.EntropyV2-calibration.table ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.EntropyV2-calibration.table "https://awf.ml.dev.web.auto/perception/models/object_detection_semseg_yolox_s/v1/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.EntropyV2-calibration.table" && echo "  OK: yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.EntropyV2-calibration.table"; } || echo "  FAIL: yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.EntropyV2-calibration.table"
[ -f ${DATA_DIR}/tensorrt_yolox/semseg_color_map.csv ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/semseg_color_map.csv "https://awf.ml.dev.web.auto/perception/models/object_detection_semseg_yolox_s/v1/semseg_color_map.csv" && echo "  OK: semseg_color_map.csv"; } || echo "  FAIL: semseg_color_map.csv"
mkdir -p ${DATA_DIR}/tensorrt_rtmdet
[ -f ${DATA_DIR}/tensorrt_rtmdet/tensorrt_rtmdet_onnx_models.tar.gz ] || { wget -q -O ${DATA_DIR}/tensorrt_rtmdet/tensorrt_rtmdet_onnx_models.tar.gz "https://autoware-files.s3.us-west-2.amazonaws.com/models/tensorrt_rtmdet_onnx_models.tar.gz" && echo "  OK: tensorrt_rtmdet_onnx_models.tar.gz"; } || echo "  FAIL: tensorrt_rtmdet_onnx_models.tar.gz"
tar xzf ${DATA_DIR}/tensorrt_rtmdet/tensorrt_rtmdet_onnx_models.tar.gz -C ${DATA_DIR}/tensorrt_rtmdet/ 2>/dev/null || true
[ -f ${DATA_DIR}/tensorrt_yolox/yolox_s_car_ped_tl_detector_960_960_batch_1.onnx ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/yolox_s_car_ped_tl_detector_960_960_batch_1.onnx "https://awf.ml.dev.web.auto/perception/models/tl_detector_yolox_s/v1/yolox_s_car_ped_tl_detector_960_960_batch_1.onnx" && echo "  OK: yolox_s_car_ped_tl_detector_960_960_batch_1.onnx"; } || echo "  FAIL: yolox_s_car_ped_tl_detector_960_960_batch_1.onnx"
[ -f ${DATA_DIR}/tensorrt_yolox/yolox_s_car_ped_tl_detector_960_960_batch_1.EntropyV2-calibration.table ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/yolox_s_car_ped_tl_detector_960_960_batch_1.EntropyV2-calibration.table "https://awf.ml.dev.web.auto/perception/models/tl_detector_yolox_s/v1/yolox_s_car_ped_tl_detector_960_960_batch_1.EntropyV2-calibration.table" && echo "  OK: yolox_s_car_ped_tl_detector_960_960_batch_1.EntropyV2-calibration.table"; } || echo "  FAIL: yolox_s_car_ped_tl_detector_960_960_batch_1.EntropyV2-calibration.table"
[ -f ${DATA_DIR}/tensorrt_yolox/car_ped_tl_detector_labels.txt ] || { wget -q -O ${DATA_DIR}/tensorrt_yolox/car_ped_tl_detector_labels.txt "https://awf.ml.dev.web.auto/perception/models/tl_detector_yolox_s/v1/car_ped_tl_detector_labels.txt" && echo "  OK: car_ped_tl_detector_labels.txt"; } || echo "  FAIL: car_ped_tl_detector_labels.txt"
mkdir -p ${DATA_DIR}/traffic_light_classifier
[ -f ${DATA_DIR}/traffic_light_classifier/traffic_light_classifier_mobilenetv2_batch_1.onnx ] || { wget -q -O ${DATA_DIR}/traffic_light_classifier/traffic_light_classifier_mobilenetv2_batch_1.onnx "https://awf.ml.dev.web.auto/perception/models/traffic_light_classifier/v4/traffic_light_classifier_mobilenetv2_batch_1.onnx" && echo "  OK: traffic_light_classifier_mobilenetv2_batch_1.onnx"; } || echo "  FAIL: traffic_light_classifier_mobilenetv2_batch_1.onnx"
[ -f ${DATA_DIR}/traffic_light_classifier/traffic_light_classifier_mobilenetv2_batch_4.onnx ] || { wget -q -O ${DATA_DIR}/traffic_light_classifier/traffic_light_classifier_mobilenetv2_batch_4.onnx "https://awf.ml.dev.web.auto/perception/models/traffic_light_classifier/v4/traffic_light_classifier_mobilenetv2_batch_4.onnx" && echo "  OK: traffic_light_classifier_mobilenetv2_batch_4.onnx"; } || echo "  FAIL: traffic_light_classifier_mobilenetv2_batch_4.onnx"
[ -f ${DATA_DIR}/traffic_light_classifier/traffic_light_classifier_mobilenetv2_batch_6.onnx ] || { wget -q -O ${DATA_DIR}/traffic_light_classifier/traffic_light_classifier_mobilenetv2_batch_6.onnx "https://awf.ml.dev.web.auto/perception/models/traffic_light_classifier/v4/traffic_light_classifier_mobilenetv2_batch_6.onnx" && echo "  OK: traffic_light_classifier_mobilenetv2_batch_6.onnx"; } || echo "  FAIL: traffic_light_classifier_mobilenetv2_batch_6.onnx"
[ -f ${DATA_DIR}/traffic_light_classifier/ped_traffic_light_classifier_mobilenetv2_batch_1.onnx ] || { wget -q -O ${DATA_DIR}/traffic_light_classifier/ped_traffic_light_classifier_mobilenetv2_batch_1.onnx "https://awf.ml.dev.web.auto/perception/models/traffic_light_classifier/v4/ped_traffic_light_classifier_mobilenetv2_batch_1.onnx" && echo "  OK: ped_traffic_light_classifier_mobilenetv2_batch_1.onnx"; } || echo "  FAIL: ped_traffic_light_classifier_mobilenetv2_batch_1.onnx"
[ -f ${DATA_DIR}/traffic_light_classifier/ped_traffic_light_classifier_mobilenetv2_batch_4.onnx ] || { wget -q -O ${DATA_DIR}/traffic_light_classifier/ped_traffic_light_classifier_mobilenetv2_batch_4.onnx "https://awf.ml.dev.web.auto/perception/models/traffic_light_classifier/v4/ped_traffic_light_classifier_mobilenetv2_batch_4.onnx" && echo "  OK: ped_traffic_light_classifier_mobilenetv2_batch_4.onnx"; } || echo "  FAIL: ped_traffic_light_classifier_mobilenetv2_batch_4.onnx"
[ -f ${DATA_DIR}/traffic_light_classifier/ped_traffic_light_classifier_mobilenetv2_batch_6.onnx ] || { wget -q -O ${DATA_DIR}/traffic_light_classifier/ped_traffic_light_classifier_mobilenetv2_batch_6.onnx "https://awf.ml.dev.web.auto/perception/models/traffic_light_classifier/v4/ped_traffic_light_classifier_mobilenetv2_batch_6.onnx" && echo "  OK: ped_traffic_light_classifier_mobilenetv2_batch_6.onnx"; } || echo "  FAIL: ped_traffic_light_classifier_mobilenetv2_batch_6.onnx"
[ -f ${DATA_DIR}/traffic_light_classifier/lamp_labels.txt ] || { wget -q -O ${DATA_DIR}/traffic_light_classifier/lamp_labels.txt "https://awf.ml.dev.web.auto/perception/models/traffic_light_classifier/v4/lamp_labels.txt" && echo "  OK: lamp_labels.txt"; } || echo "  FAIL: lamp_labels.txt"
[ -f ${DATA_DIR}/traffic_light_classifier/lamp_labels_ped.txt ] || { wget -q -O ${DATA_DIR}/traffic_light_classifier/lamp_labels_ped.txt "https://awf.ml.dev.web.auto/perception/models/traffic_light_classifier/v4/lamp_labels_ped.txt" && echo "  OK: lamp_labels_ped.txt"; } || echo "  FAIL: lamp_labels_ped.txt"
[ -f ${DATA_DIR}/traffic_light_classifier/traffic_light_lamp_recognizer_comlops.onnx ] || { wget -q -O ${DATA_DIR}/traffic_light_classifier/traffic_light_lamp_recognizer_comlops.onnx "https://awf.ml.dev.web.auto/perception/models/traffic_light_classifier/v4/traffic_light_lamp_recognizer_comlops.onnx" && echo "  OK: traffic_light_lamp_recognizer_comlops.onnx"; } || echo "  FAIL: traffic_light_lamp_recognizer_comlops.onnx"
mkdir -p ${DATA_DIR}/diffusion_planner/v3.0
[ -f ${DATA_DIR}/diffusion_planner/v3.0/diffusion_planner.onnx ] || { wget -q -O ${DATA_DIR}/diffusion_planner/v3.0/diffusion_planner.onnx "https://awf.ml.dev.web.auto/planning/models/diffusion_planner/v3.0/diffusion_planner.onnx" && echo "  OK: diffusion_planner.onnx"; } || echo "  FAIL: diffusion_planner.onnx"
[ -f ${DATA_DIR}/diffusion_planner/v3.0/diffusion_planner.param.json ] || { wget -q -O ${DATA_DIR}/diffusion_planner/v3.0/diffusion_planner.param.json "https://awf.ml.dev.web.auto/planning/models/diffusion_planner/v3.0/diffusion_planner.param.json" && echo "  OK: diffusion_planner.param.json"; } || echo "  FAIL: diffusion_planner.param.json"
mkdir -p ${DATA_DIR}/diffusion_planner/v3.1
[ -f ${DATA_DIR}/diffusion_planner/v3.1/diffusion_planner.onnx ] || { wget -q -O ${DATA_DIR}/diffusion_planner/v3.1/diffusion_planner.onnx "https://awf.ml.dev.web.auto/planning/models/diffusion_planner/v3.1/diffusion_planner.onnx" && echo "  OK: diffusion_planner.onnx"; } || echo "  FAIL: diffusion_planner.onnx"
[ -f ${DATA_DIR}/diffusion_planner/v3.1/diffusion_planner.param.json ] || { wget -q -O ${DATA_DIR}/diffusion_planner/v3.1/diffusion_planner.param.json "https://awf.ml.dev.web.auto/planning/models/diffusion_planner/v3.1/diffusion_planner.param.json" && echo "  OK: diffusion_planner.param.json"; } || echo "  FAIL: diffusion_planner.param.json"
mkdir -p ${DATA_DIR}/diffusion_planner/v4.0
[ -f ${DATA_DIR}/diffusion_planner/v4.0/diffusion_planner.onnx ] || { wget -q -O ${DATA_DIR}/diffusion_planner/v4.0/diffusion_planner.onnx "https://awf.ml.dev.web.auto/planning/models/diffusion_planner/v4.0/diffusion_planner.onnx" && echo "  OK: diffusion_planner.onnx"; } || echo "  FAIL: diffusion_planner.onnx"
[ -f ${DATA_DIR}/diffusion_planner/v4.0/diffusion_planner.param.json ] || { wget -q -O ${DATA_DIR}/diffusion_planner/v4.0/diffusion_planner.param.json "https://awf.ml.dev.web.auto/planning/models/diffusion_planner/v4.0/diffusion_planner.param.json" && echo "  OK: diffusion_planner.param.json"; } || echo "  FAIL: diffusion_planner.param.json"
mkdir -p ${DATA_DIR}/vad/v0.1
[ -f ${DATA_DIR}/vad/v0.1/vad-carla-tiny_backbone.onnx ] || { wget -q -O ${DATA_DIR}/vad/v0.1/vad-carla-tiny_backbone.onnx "https://awf.ml.dev.web.auto/planning/models/tensorrt_vad/carla_tiny/v0.1/vad-carla-tiny_backbone.onnx" && echo "  OK: vad-carla-tiny_backbone.onnx"; } || echo "  FAIL: vad-carla-tiny_backbone.onnx"
[ -f ${DATA_DIR}/vad/v0.1/vad-carla-tiny_head.onnx ] || { wget -q -O ${DATA_DIR}/vad/v0.1/vad-carla-tiny_head.onnx "https://awf.ml.dev.web.auto/planning/models/tensorrt_vad/carla_tiny/v0.1/vad-carla-tiny_head.onnx" && echo "  OK: vad-carla-tiny_head.onnx"; } || echo "  FAIL: vad-carla-tiny_head.onnx"
[ -f ${DATA_DIR}/vad/v0.1/vad-carla-tiny_head_no_prev.onnx ] || { wget -q -O ${DATA_DIR}/vad/v0.1/vad-carla-tiny_head_no_prev.onnx "https://awf.ml.dev.web.auto/planning/models/tensorrt_vad/carla_tiny/v0.1/vad-carla-tiny_head_no_prev.onnx" && echo "  OK: vad-carla-tiny_head_no_prev.onnx"; } || echo "  FAIL: vad-carla-tiny_head_no_prev.onnx"
[ -f ${DATA_DIR}/vad/v0.1/vad-carla-tiny.param.json ] || { wget -q -O ${DATA_DIR}/vad/v0.1/vad-carla-tiny.param.json "https://awf.ml.dev.web.auto/planning/models/tensorrt_vad/carla_tiny/v0.1/vad-carla-tiny.param.json" && echo "  OK: vad-carla-tiny.param.json"; } || echo "  FAIL: vad-carla-tiny.param.json"
mkdir -p ${DATA_DIR}/traffic_light_fine_detector
[ -f ${DATA_DIR}/traffic_light_fine_detector/tlr_car_ped_yolox_s_batch_1.onnx ] || { wget -q -O ${DATA_DIR}/traffic_light_fine_detector/tlr_car_ped_yolox_s_batch_1.onnx "https://awf.ml.dev.web.auto/perception/models/tlr_yolox_s/v3/tlr_car_ped_yolox_s_batch_1.onnx" && echo "  OK: tlr_car_ped_yolox_s_batch_1.onnx"; } || echo "  FAIL: tlr_car_ped_yolox_s_batch_1.onnx"
[ -f ${DATA_DIR}/traffic_light_fine_detector/tlr_car_ped_yolox_s_batch_4.onnx ] || { wget -q -O ${DATA_DIR}/traffic_light_fine_detector/tlr_car_ped_yolox_s_batch_4.onnx "https://awf.ml.dev.web.auto/perception/models/tlr_yolox_s/v3/tlr_car_ped_yolox_s_batch_4.onnx" && echo "  OK: tlr_car_ped_yolox_s_batch_4.onnx"; } || echo "  FAIL: tlr_car_ped_yolox_s_batch_4.onnx"
[ -f ${DATA_DIR}/traffic_light_fine_detector/tlr_car_ped_yolox_s_batch_6.onnx ] || { wget -q -O ${DATA_DIR}/traffic_light_fine_detector/tlr_car_ped_yolox_s_batch_6.onnx "https://awf.ml.dev.web.auto/perception/models/tlr_yolox_s/v3/tlr_car_ped_yolox_s_batch_6.onnx" && echo "  OK: tlr_car_ped_yolox_s_batch_6.onnx"; } || echo "  FAIL: tlr_car_ped_yolox_s_batch_6.onnx"
[ -f ${DATA_DIR}/traffic_light_fine_detector/tlr_labels.txt ] || { wget -q -O ${DATA_DIR}/traffic_light_fine_detector/tlr_labels.txt "https://awf.ml.dev.web.auto/perception/models/tlr_yolox_s/v3/tlr_labels.txt" && echo "  OK: tlr_labels.txt"; } || echo "  FAIL: tlr_labels.txt"
mkdir -p ${DATA_DIR}/simpl_prediction
[ -f ${DATA_DIR}/simpl_prediction/simpl.onnx ] || { wget -q -O ${DATA_DIR}/simpl_prediction/simpl.onnx "https://awf.ml.dev.web.auto/perception/models/simpl/v0.1.0/simpl.onnx" && echo "  OK: simpl.onnx"; } || echo "  FAIL: simpl.onnx"
mkdir -p ${DATA_DIR}/ptv3
[ -f ${DATA_DIR}/ptv3/ptv3.onnx ] || { wget -q -O ${DATA_DIR}/ptv3/ptv3.onnx "https://awf.ml.dev.web.auto/perception/models/ptv3/v2/ptv3.onnx" && echo "  OK: ptv3.onnx"; } || echo "  FAIL: ptv3.onnx"
[ -f ${DATA_DIR}/ptv3/ml_package_ptv3.param.yaml ] || { wget -q -O ${DATA_DIR}/ptv3/ml_package_ptv3.param.yaml "https://awf.ml.dev.web.auto/perception/models/ptv3/v2/ml_package_ptv3.param.yaml" && echo "  OK: ml_package_ptv3.param.yaml"; } || echo "  FAIL: ml_package_ptv3.param.yaml"
mkdir -p ${DATA_DIR}/lidar_frnet
[ -f ${DATA_DIR}/lidar_frnet/frnet_ot128.onnx ] || { wget -q -O ${DATA_DIR}/lidar_frnet/frnet_ot128.onnx "https://awf.ml.dev.web.auto/perception/models/frnet/v2/frnet_ot128.onnx" && echo "  OK: frnet_ot128.onnx"; } || echo "  FAIL: frnet_ot128.onnx"
[ -f ${DATA_DIR}/lidar_frnet/frnet_qt128.onnx ] || { wget -q -O ${DATA_DIR}/lidar_frnet/frnet_qt128.onnx "https://awf.ml.dev.web.auto/perception/models/frnet/v2/frnet_qt128.onnx" && echo "  OK: frnet_qt128.onnx"; } || echo "  FAIL: frnet_qt128.onnx"
[ -f ${DATA_DIR}/lidar_frnet/ml_package_frnet_ot128.param.yaml ] || { wget -q -O ${DATA_DIR}/lidar_frnet/ml_package_frnet_ot128.param.yaml "https://awf.ml.dev.web.auto/perception/models/frnet/v2/ml_package_frnet_ot128.param.yaml" && echo "  OK: ml_package_frnet_ot128.param.yaml"; } || echo "  FAIL: ml_package_frnet_ot128.param.yaml"
[ -f ${DATA_DIR}/lidar_frnet/ml_package_frnet_qt128.param.yaml ] || { wget -q -O ${DATA_DIR}/lidar_frnet/ml_package_frnet_qt128.param.yaml "https://awf.ml.dev.web.auto/perception/models/frnet/v2/ml_package_frnet_qt128.param.yaml" && echo "  OK: ml_package_frnet_qt128.param.yaml"; } || echo "  FAIL: ml_package_frnet_qt128.param.yaml"
mkdir -p ${DATA_DIR}/calibration_status_classifier
[ -f ${DATA_DIR}/calibration_status_classifier/calibration_status_classifier.onnx ] || { wget -q -O ${DATA_DIR}/calibration_status_classifier/calibration_status_classifier.onnx "https://awf.ml.dev.web.auto/sensing/models/calibration_status_classifier/v2/calibration_status_classifier.onnx" && echo "  OK: calibration_status_classifier.onnx"; } || echo "  FAIL: calibration_status_classifier.onnx"
[ -f ${DATA_DIR}/calibration_status_classifier/ml_package_calibration_status_classifier.param.yaml ] || { wget -q -O ${DATA_DIR}/calibration_status_classifier/ml_package_calibration_status_classifier.param.yaml "https://awf.ml.dev.web.auto/sensing/models/calibration_status_classifier/v2/ml_package_calibration_status_classifier.param.yaml" && echo "  OK: ml_package_calibration_status_classifier.param.yaml"; } || echo "  FAIL: ml_package_calibration_status_classifier.param.yaml"

echo "Done."
