#!/usr/bin/env python3

"""Generate a concise public-beta readiness report from local artifacts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml


def _load_json(path: Path) -> dict[str, Any]:
    with path.open('r', encoding='utf-8') as handle:
        return json.load(handle)


def _load_yaml(path: Path) -> Any:
    with path.open('r', encoding='utf-8') as handle:
        return yaml.safe_load(handle)


def _extract_tile_count(metadata: dict[str, Any]) -> int:
    return sum(1 for key in metadata if str(key).endswith('.pcd'))


def _extract_total_points(map_verify: dict[str, Any] | None) -> str:
    if not isinstance(map_verify, dict):
        return 'unknown'
    for line in map_verify.get('passes', []):
        if 'Total points across all tiles:' in line:
            return line.split(':', 1)[1].strip()
    return 'unknown'


def _has_rviz_subscription(log_path: Path) -> bool:
    if not log_path.is_file():
        return False
    text = log_path.read_text(encoding='utf-8', errors='replace')
    return '/map/pointcloud_map' in text and 'Subscribing to:' in text


def _fmt_float(value: Any, digits: int = 3) -> str:
    try:
        return f'{float(value):.{digits}f}'
    except Exception:
        return 'n/a'


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Generate a v2 public-beta readiness markdown report.',
    )
    parser.add_argument(
        '--benchmark-summary',
        default='output/benchmark_summary.md',
        help='Markdown benchmark summary generated by benchmark_summary.py',
    )
    parser.add_argument(
        '--fresh-metrics',
        default='output/bench_rko_lio_ntu_viral_fresh_20260324/metrics.json',
        help='metrics.json for the current default-path fresh benchmark',
    )
    parser.add_argument(
        '--best-metrics',
        default='output/bench_rko_lio_ntu_viral_loopgate_20260324/metrics.json',
        help='metrics.json for the current best benchmark run',
    )
    parser.add_argument(
        '--dogfood-dir',
        default='output/dogfood_rko_lio_autoware_20260324_190734',
        help='Output directory of the latest successful Autoware dogfood run',
    )
    parser.add_argument(
        '--out',
        default='output/v2_beta_readiness_20260324.md',
        help='Markdown report output path',
    )
    args = parser.parse_args()

    summary_path = Path(args.benchmark_summary).expanduser().resolve()
    fresh_metrics_path = Path(args.fresh_metrics).expanduser().resolve()
    best_metrics_path = Path(args.best_metrics).expanduser().resolve()
    dogfood_dir = Path(args.dogfood_dir).expanduser().resolve()
    out_path = Path(args.out).expanduser().resolve()

    summary_text = summary_path.read_text(encoding='utf-8')
    fresh = _load_json(fresh_metrics_path)
    best = _load_json(best_metrics_path)

    metadata_path = dogfood_dir / 'pointcloud_map' / 'pointcloud_map_metadata.yaml'
    projector_path = dogfood_dir / 'map_projector_info.yaml'
    rviz_log_path = next(
        iter(sorted((dogfood_dir / '.ros_log').glob('rviz2_*.log'))),
        None,
    )

    metadata = _load_yaml(metadata_path)
    projector = _load_yaml(projector_path)

    fresh_ape = ((fresh.get('evo') or {}).get('ape') or {})
    best_ape = ((best.get('evo') or {}).get('ape') or {})
    fresh_map_verify = ((fresh.get('graph_based_slam') or {}).get('map_verify') or {})

    rviz_ok = _has_rviz_subscription(rviz_log_path) if rviz_log_path else False
    projector_type = projector.get('projector_type', 'UNKNOWN')
    tile_count = _extract_tile_count(metadata)
    fresh_total_points = _extract_total_points(fresh_map_verify)

    report = f"""# v2 Beta Readiness Report

Date: 2026-03-24

## Verdict

`lidarslam_ros2` is in a reasonable state for a public `v2 beta` release.

The current default path is:

- `RKO-LIO + graph_based_slam`
- Autoware-compatible pointcloud map export
- pointcloud-only Autoware dogfood

## Evidence

### Benchmark Snapshot

- default-path fresh run APE RMSE: `{_fmt_float(fresh_ape.get('rmse'))} m`
- current best run APE RMSE: `{_fmt_float(best_ape.get('rmse'))} m`
- fresh run wall time: `{_fmt_float(((fresh.get('lidarslam') or {}).get('wall_sec')), 2)} s`
- fresh run RTF: `{_fmt_float(((fresh.get('lidarslam') or {}).get('rtf')), 3)}`
- fresh run map verify: `{"PASS" if fresh_map_verify.get('ok') else "FAIL"}`
- fresh run total map points: `{fresh_total_points}`

Benchmark summary artifact:

- `{summary_path}`

### Pointcloud Map Snapshot

- dogfood output dir: `{dogfood_dir}`
- `map_projector_info.yaml`: `projector_type: {projector_type}`
- pointcloud tiles: `{tile_count}`
- map grid resolution: `{metadata.get('x_resolution')} m x {metadata.get('y_resolution')} m`
- host `rviz2` subscribed to `/map/pointcloud_map`: `{"yes" if rviz_ok else "no"}`

Relevant dogfood artifacts:

- `{projector_path}`
- `{metadata_path}`
- `{dogfood_dir / 'slam.launch.log'}`

### Existing Reports

- markdown summary: `{summary_path}`
- HTML report: `{summary_path.parent / 'latest_report.html'}`

## Why This Looks Good Enough

- all current benchmark runs in `output/benchmark_summary.md` are under the
  local `1.0 m` APE gate
- the default fresh benchmark is no longer the obviously bad outlier it was
  before the launch/config fixes
- the generated pointcloud map is structured as an Autoware bundle and has a
  current local verification pass
- the Autoware dogfood run saved a multi-tile pointcloud map and `rviz2`
  subscribed to `/map/pointcloud_map`

## Remaining Caveats

- pointcloud-map flow is validated; lanelet generation is still out of scope
- the dogfood sample above is `projector_type: Local` because GNSS was not used
- current evidence is strong enough for a public beta, not for claiming
  production maturity
- remote GitHub Actions still need to be run on the final release branch/commit

## Source Artifacts

- fresh metrics: `{fresh_metrics_path}`
- best metrics: `{best_metrics_path}`
- benchmark summary: `{summary_path}`
- latest HTML report: `{summary_path.parent / 'latest_report.html'}`
"""

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding='utf-8')
    print(out_path)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
